version: 2.1

executors:
  elixir:
    docker:
      - image: hexpm/elixir:1.17.3-erlang-26.2.5.5-ubuntu-noble-20240801
    environment:
      MIX_ENV: test
    working_directory: ~/app

jobs:
  build:
    executor: elixir
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      
      # Update package lists to avoid 404 errors
      - run:
          name: Update apt packages
          command: |
            apt-get update
            apt-get install -y git curl build-essential

      - restore_cache:
          keys:
            - v15-mix-cache-{{ checksum "mix.lock" }}
            - v15-mix-cache-

      - run: echo 'export PATH=~/.cargo/bin:$PATH' >> $BASH_ENV

      # Install Rust for NIFs
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Install dependencies
          command: mix deps.get

      - run:
          name: Compile dependencies
          command: mix deps.compile

      - save_cache:
          key: v15-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build

      - run:
          name: Compile project
          command: mix compile --warnings-as-errors

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: elixir
    steps:
      - attach_workspace:
          at: .
          
      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Run tests
          command: mix test --exclude pending --exclude slow

  credo:
    executor: elixir
    steps:
      - attach_workspace:
          at: .
          
      - run:
          name: Install hex
          command: mix local.hex --force

      - run:
          name: Run Credo
          command: mix credo --strict --only readability,consistency,warning,refactor

  format:
    executor: elixir
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Check formatting
          command: mix format --check-formatted

  dialyzer:
    executor: elixir
    steps:
      - attach_workspace:
          at: .
          
      - run:
          name: Install hex and rebar
          command: |
            mix local.hex --force
            mix local.rebar --force

      - restore_cache:
          keys:
            - v15-plt-cache-{{ checksum "mix.lock" }}
            - v15-plt-cache-

      - run:
          name: Create PLT directory
          command: mkdir -p _build/test

      - run:
          name: Build PLT
          command: mix dialyzer --plt

      - save_cache:
          key: v15-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build/test/*.plt*

      - run:
          name: Run Dialyzer
          command: mix dialyzer --format short

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - credo:
          requires:
            - build
      - format:
          requires:
            - build
      - dialyzer:
          requires:
            - build